### ISSUE TITLE
Crash when playing on LAN

### ISSUE THREAD

**Issue by SabinaArmalite** [Globox1997/EnvironmentZ#22]
[15:01:50] [Render thread/INFO]: Loaded 636 advancements
[15:01:50] [Render thread/INFO]: Player cosmetics successfully registered
[15:01:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SayGon]'/minecraft:the_nether
[15:01:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SayGon]'/minecraft:the_end
[15:01:54] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.cod.ambient
[15:01:54] [Server thread/INFO]: Saving and pausing game...
[15:01:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SayGon]'/minecraft:overworld
[15:01:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SayGon]'/minecraft:the_nether
[15:01:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[SayGon]'/minecraft:the_end
[15:02:00] [Render thread/INFO]: Using default channel type
[15:02:00] [Render thread/INFO]: Started serving on 49184
[15:02:00] [Render thread/INFO]: [CHAT] Local game hosted on port 49184
[15:02:22] [Render thread/INFO]: Loaded 637 advancements
[15:03:29] [Server thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[15:03:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3242.method_14357(class_3242.java:186) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:904) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.class_1324.method_6197(class_1324.java:73) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_1324.method_26837(class_1324.java:85) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.environmentz.effect.OverheatingEffect.method_5555(OverheatingEffect.java:46) ~[environmentz-1.1.4.jar:?]
	at net.minecraft.class_1309.handler$zhn000$checkStatus(class_1309.java:4570) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_1309.method_6009(class_1309.java) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_3222.method_6009(class_3222.java:1215) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_1309.method_37222(class_1309.java:953) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_1309.method_6092(class_1309.java:937) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.environmentz.util.TemperatureAspects.hotEnvironment(TemperatureAspects.java:64) ~[environmentz-1.1.4.jar:?]
	at net.minecraft.class_1657.handler$bdh002$tickMixin(class_1657.java:6330) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:323) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:469) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:213) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
	... 6 more
[15:03:29] [Server thread/ERROR]: This crash report has been saved to: C:\Users\hp\AppData\Roaming\.minecraft\crash-reports\crash-2021-07-18_15.03.29-server.txt
[15:03:29] [Server thread/INFO]: Stopping server
[15:03:29] [Server thread/INFO]: Saving players
[15:03:29] [Server thread/INFO]: SabinaArmalite lost connection: Disconnected
[15:03:29] [Server thread/INFO]: SabinaArmalite left the game
[15:03:29] [Thread-135/INFO]: Minecraft instance shutting down, starting the Illuminations uninstaller

**Comment by Globox1997** [comment]
should be fixed with a later version, if still happening, pls open again with the full crash log
