### ISSUE TITLE
Crash on startup with quite a bit of mods

### ISSUE THREAD

**Issue by InsaanNotFound** [Globox1997/EnvironmentZ#3]
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2021-01-22 17:07:12 CET
Description: Initializing game

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.minecraft.item.ArmorItem.appendTooltip(ArmorItem:1032)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack:631)
    at net.minecraft.client.MinecraftClient.method_1485(MinecraftClient:717)
    at net.minecraft.client.search.TextSearchableContainer.index(TextSearchableContainer:36)
    at net.minecraft.client.search.IdentifierSearchableContainer.add(IdentifierSearchableContainer:48)
    at net.minecraft.client.MinecraftClient.method_1535(MinecraftClient:730)
    at java.lang.Iterable.forEach(Unknown Source)
    at net.minecraft.client.MinecraftClient.initializeSearchableContainers(MinecraftClient:729)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:544)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

Mixins in stacktrace:
```
net.minecraft.class_1738:
                        com.exline.woodarmor.mixin.ArmorItemMixin (woodarmor.mixins.json)
                        io.github.apace100.origins.mixin.ArmorItemMixin (origins.mixins.json)
                        net.environmentz.mixin.ArmorItemMixin (environmentz.mixins.json)
                        net.minecraft.class_1799:
                        com.hugman.dawn.mod.mixin.ItemStackMixin (dawn_mod.mixins.json)
                        draylar.inmis.mixin.ItemStackMixin (inmis.mixins.json)
                        net.telepathicgrunt.bumblezone.mixin.items.HoneyShieldItemstackGetMaximumDamageMixin (the_bumblezone.mixins.json)
                        top.theillusivec4.colytra.loader.mixin.ItemStackMixin (colytra.mixins.json)
                        net.telepathicgrunt.bumblezone.mixin.items.HoneyShieldItemstackSetDamageMixin (the_bumblezone.mixins.json)
                        net.fabricmc.fabric.mixin.tool.attribute.MixinItemStack (fabric-tool-attribute-api-v1.mixins.json)
                        com.focamacho.ringsofascension.mixin.ItemStackMixin (ringsofascension.mixins.json)
                        net.fabricmc.fabric.mixin.item.ItemStackMixin (fabric-item-api-v1.mixins.json)
                        net.tigereye.spellbound.mixins.ItemStackMixin (spellbound.mixins.json)
                        io.teamblue.composing.mixin.ItemStackEAMMixin (mixins.composing.json)
                        net.fabricmc.fabric.mixin.item.client.ItemStackMixin (fabric-item-api-v1.mixins.json)
                        de.siphalor.nbtcrafting.mixin.MixinItemStack (nbtcrafting.mixins.json)
                        dev.onyxstudios.cca.mixin.item.common.MixinItemStack (mixins.cardinal_components_item.json)
                        azmalent.potiondescriptions.mixin.ItemStackMixin (potiondescriptions.mixins.json)
                        top.theillusivec4.curios.mixin.ItemStackMixin (curios.mixins.json)
                        io.github.apace100.originsclasses.mixin.DontOverwriteAttrModsMixin (origins-classes.mixins.json)
                        artifacts.mixin.mixins.accessors.ItemStackAccessor (artifacts.mixins.json)
                        tfar.dankstorage.mixin.ItemStackMixin (dankstorage.mixins.json)
                        is.rmob.supershulkers.mixin.ItemStackMixin (supershulkers.mixins.json)
                        com.glisco.conjuring.mixin.TooltipMixin (conjuring.mixins.json)
                        io.github.apace100.origins.mixin.ItemStackMixin (origins.mixins.json)
                        dev.emi.trinkets.mixin.ItemStackMixin (trinkets.mixins.json)
                        dzwdz.durability_banks.mixin.ItemStackMixin (durability_banks.mixins.json)
                        net.minecraft.class_310:
                        tfar.dankstorage.mixin.MinecraftClientAccessor (dankstorage.mixins.json)
                        dynamicfps.mixin.MinecraftClientMixin (dynamicfps.mixins.json)
                        com.swordglowsblue.artifice.mixin.MixinMinecraftClient (artifice.mixins.json)
                        dev.emi.bunchotrinkets.mixin.MinecraftClientMixin (bunchotrinkets.mixins.json)
                        net.fabricmc.fabric.mixin.event.interaction.MixinMinecraftClient (fabric-events-interaction-v0.mixins.json)
                        ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
                        badasintended.cpas.mixin.MixinMinecraftClient (cpas.mixins.json)
                        fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json)
                        me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (mixins.fabrishot.json)
                        io.github.lucaargolo.slotlock.mixin.MinecraftClientMixin (slotlock.mixins.json)
                        me.shedaniel.cloth.mixin.client.events.MixinMinecraftClient (cloth-client-events-v0.mixins.json)
                        me.jellysquid.mods.sodium.mixin.options.MixinMinecraftClient (sodium.mixins.json)
                        svenhjol.charm.mixin.MinecraftClientMixin (charm.mixins.json)
                        net.boostedbrightness.mixin.MixinMinecraftClient (boostedbrightness.mixins.json)
                        squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
                        io.github.giantnuker.fabric.loadcatcher.mixin.MinecraftClientMixin (loadcatcher.mixins.json)
                        com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
                        net.ludocrypt.dynmus.mixin.MinecraftClientMixin (dynmus.mixins.json)
                        vazkii.patchouli.mixin.client.MixinMinecraftClient (patchouli.mixins.json)
                        ru.betterend.mixin.client.MinecraftClientMixin (betterend.mixins.client.json)
                        net.clayborn.accurateblockplacement.mixin.MinecraftClientMixin (accurateblockplacement.mixins.json)
                        com.rdvdev2.disablecustomworldsadvice.mixin.MixinMinecraftClient (disable_custom_worlds_advice.mixins.json)
                        net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.mixins.json)
                        me.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
                        net.fabricmc.fabric.mixin.registry.sync.client.MixinMinecraftClient (fabric-registry-sync-v0.mixins.json)
                        me.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
                        com.github.legoatoom.connectiblechains.mixin.client.MinecraftClientMixin (connectiblechains.mixins.json)
                        net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.mixins.json)
                        me.hypherionmc.simplerpc.mixin.ScreenEventsMixin (simple-rpc.mixins.json)
                        me.shedaniel.advancementsenlarger.mixin.MixinMinecraftClient (advancements-enlarger.mixins.json)
                        com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
                        top.theillusivec4.polymorph.loader.mixin.core.MinecraftClientAccessor (polymorph.mixins.json)
                        tfar.dankstorage.mixin.MinecraftClientMixin (dankstorage.mixins.json)
                        me.shedaniel.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
                        carpet.mixins.MinecraftClient_pausedShakeMixin (carpet.mixins.json)
                        io.github.joaoh1.okzoomer.client.mixin.MinecraftClientMixin (okzoomer.mixins.json)
                        de.siphalor.nbtcrafting.mixin.client.MixinMinecraftClient (nbtcrafting.mixins.json)
                        xaero.map.mixin.MixinMinecraftClient (xaeroworldmap.mixins.json)
                        com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (mixins.jgui.json)
                        svenhjol.charm.mixin.accessor.MinecraftClientAccessor (charm.mixins.json)
                        net.johnvictorfs.simple_utilities.mixin.GameClientMixin (simple_utilities.mixins.json)
                        me.shedaniel.slightguimodifications.mixin.MixinMinecraft (slight-gui-modifications.mixins.json)
                        carpet.mixins.MinecraftClientMixin (carpet.mixins.json)
                        dev.latvian.kubejs.mixin.common.MinecraftMixin (kubejs-common.mixins.json)
```

**Comment by user11681** [comment]
The problem appears to be EnvironmentZ's implementation of `appendTooltip` on `ArmorItem` uses `ItemStack#getTag`, which is annotated with `@Nullable`, without checking if `null` is returned.

**Comment by Globox1997** [comment]
oh yes this can happen, thought armor items always have a tag

**Comment by Globox1997** [comment]
pls check the newest version
[https://www.curseforge.com/minecraft/mc-mods/environmentz/files/3177607](https://www.curseforge.com/minecraft/mc-mods/environmentz/files/3177607)

**Comment by InsaanNotFound** [comment]
It works now, thank you! :)
