### ISSUE TITLE
HeatedStone at 0 durability cause connection lost

### ISSUE THREAD

**Issue by MokkaCicc** [Globox1997/EnvironmentZ#6]
In a multiplayer server, when a player uses a heated stone and its durability reaches 0, the server can't handle the packet, crashing the player instance. The player cannot reconnect until the stone is removed from his inventory.

logs:
[21:38:16] [Server thread/WARN]: Failed to handle packet for /25.91.8.179:62895
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'int net.minecraft.class_1661.method_7395(net.minecraft.class_1799)'
	at net.environmentz.item.HeatedStones.method_7888(HeatedStones.java:30) ~[environmentz-1.0.10.jar:?]

**Comment by Globox1997** [comment]
Fixed it with [https://github.com/Globox1997/EnvironmentZ/commit/0ef5fe111cbe9da3eed2098e19abad194b28e1d1](https://github.com/Globox1997/EnvironmentZ/commit/0ef5fe111cbe9da3eed2098e19abad194b28e1d1)
