### ISSUE TITLE
EnvironmentZ Is Dividing By 0

### ISSUE THREAD

**Issue by chronosacaria** [Globox1997/EnvironmentZ#63]
Hey Globox_Z! So, some people have mentioned that they are experiencing an issue with EnvironmentZ trying to divide by 0 when they get cold. I have attached a crashlog from one such player. If there is anything I can do to help with this, just lemme know. This is the general gist, though:

```
java.lang.ArithmeticException: / by zero
	at net.minecraft.client.render.GameRenderer.handler$eeh000$renderWorldMixin(GameRenderer.java:4539)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1012)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768)
	at net.minecraft.client.main.Main.main(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
[crash-2022-09-08_22.35.46-client.txt](https://github.com/Globox1997/EnvironmentZ/files/9542598/crash-2022-09-08_22.35.46-client.txt)

**Comment by ericlin11354** [comment]
Having the same issue as well

**Comment by StellaBiscuit** [comment]
Yup, happens when your temperature is -240 and BOOM instant infinite crash

**Comment by tlalani** [comment]
same here

happened as soon as I started taking damage from freezing.

**Comment by Globox1997** [comment]
Update to 1.3.2
