### ISSUE TITLE
crash with Origins->Requiem

### ISSUE THREAD

**Issue by Vulpino** [Globox1997/EnvironmentZ#7]
Hi, i see a crash with demon entity, when the freeze try to hurt a demon

**Comment by Globox1997** [comment]
Could you send me the crash log please :)

**Comment by Vulpino** [comment]
here i got the log, i see is an error there are only appear with a demon or a soul in a winter zone

---- Minecraft Crash Report ----
// My bad.

Time: 25/03/21 20:40
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.class_1548 cannot be cast to net.minecraft.class_1657
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at net.environmentz.effect.ColdEffect.applyUpdateEffect(ColdEffect.java:35)
	at net.minecraft.entity.effect.StatusEffectInstance.applyUpdateEffect(StatusEffectInstance:169)
	at net.minecraft.entity.effect.StatusEffectInstance.update(StatusEffectInstance:148)
	at net.minecraft.entity.LivingEntity.tickStatusEffects(LivingEntity:727)
	at net.minecraft.entity.LivingEntity.baseTick(LivingEntity:412)
	at net.minecraft.entity.mob.MobEntity.baseTick(MobEntity:275)
	at net.minecraft.entity.Entity.tick(Entity:431)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2209)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:342)
	at net.minecraft.entity.mob.CreeperEntity.tick(CreeperEntity:157)
	at net.minecraft.client.world.ClientWorld.tickEntity(ClientWorld:193)
	at net.minecraft.class_638$$Lambda$7665/870493535.accept(Unknown Source)
	at net.minecraft.world.World.tickEntity(World:561)
	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:164)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1556)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.class_1548)
	Entity ID: 1013
	Entity Name: Creeper
	Entity's Exact location: 624.52, 68.00, 1098.83
	Entity's Block location: World: (624,68,1098), Chunk: (at 0,4,10 in 39,68; contains blocks 624,0,1088 to 639,255,1103), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Brain:{memories:{}},WetTimer:0,HurtByTimestamp:0,Attributes:[{Base:0.0d,Name:"stepheightentityattribute:stepheight"},{Base:0.0d,Name:"minecraft:generic.armor"},{Base:2.0d,Name:"minecraft:generic.attack_damage"},{Base:0.25d,Name:"minecraft:generic.movement_speed"},{Base:20.0d,Name:"minecraft:generic.max_health"}],Invulnerable:0b,FallFlying:0b,InsanityTargetUUID:"",PortalCooldown:0,AbsorptionAmount:0.0f,Blood:100,FallDistance:0.0f,DeathTime:0s,IsFamiliar:0b,HandDropChances:[0.085f,0.085f],PersistenceRequired:1b,UUID:[I;-1605443943,1351895690,-1316347213,-1187585434],Contracts:[],Fuse:30s,Motion:[0.0d,0.0d,0.0d],AffectedByWar:0b,Health:15.0f,LeftHanded:0b,Air:300s,OnGround:0b,ignited:0b,Rotation:[122.34375f,19.6875f],HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[624.5186923317219d,68.0d,1098.8317498843865d],Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,Curses:[],HurtTime:0s,ExplosionRadius:3b,ActiveEffects:[{Ambient:0b,ShowIcon:1b,ShowParticles:0b,Duration:2400,Id:80b,Amplifier:0b},{Ambient:0b,ShowIcon:1b,ShowParticles:0b,Duration:300,Id:82b,Amplifier:0b}],CustomNameVisible:0b}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:564)
	at net.minecraft.class_638.method_18116(class_638.java:164)
	at net.minecraft.class_310.method_1574(class_310.java:1556)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Globox1997** [comment]
Super weird, one of your mods is trying to tick the PlayerEntity tick on a CreeperEntity o.O it's an easy fix but this should never happen

**Comment by Globox1997** [comment]
Ups, I have overlooked something..
Fixed with [https://github.com/Globox1997/EnvironmentZ/commit/cfb209ba4d0eb6887fcebf858765c72a2b33eb6b](https://github.com/Globox1997/EnvironmentZ/commit/cfb209ba4d0eb6887fcebf858765c72a2b33eb6b)

**Comment by Vulpino** [comment]
Nice, i put in my server again then, thank you very much ^^
