### ISSUE TITLE
Autolog Convention

### ISSUE THREAD

**Issue by Lappy08** [Globox1997/EnvironmentZ#98]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.19

### Mod Version

2.0.5

### Describe the Issue

The error log told me to install something called autolog convetion, whats that?

### latest.log

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install autotag-convention, version 2.0.0+1.19 or later.
Unmet dependency listing:
	 - Mod 'EnvironmentZ' (environmentz) 2.0.5 requires version 2.0.0+1.19 or later of autotag-convention, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Globox1997** [comment]
Check the dependency tab on the respective website.
[https://modrinth.com/mod/autotag](https://modrinth.com/mod/autotag)
